version: '3.2'

networks:
  public_overlay:
    driver: overlay
    external: false
  agent_overlay:
    driver: overlay
    external: false
  control_overlay:
    driver: overlay
    external: false

volumes:
  datastore_config: 
  datastore_portainer:
  # datastore_teleport:

configs:
  traefik_config:
    file: ./traefik.yml
      # - ./control_plane.yml
      # - ./acme.json
      # - ./config/*
  # my_other_config:
  #   external: true

services:
  cloud_cli:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: docker/dev-environments-default:stable-1
    # privileged: true
    # interactive: true
    # tty: true
    # user: cspadmin    
    environment:
      - BUILD_DIR=$HOME/CloudServices
    command: 
      - git config --global user.name "PICTC"
      - git config --global user.email "support@premier-ictc.com"
      - git clone https://github.com/PREMIER-ICT-CONSULTING/CloudServices.git
      - cd "CloudServices"
    # ports:
    #   - "22"
    networks:
      - "control_overlay"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datastore_config:$HOME/CloudServices
      - /var/snap/traefik/common:$HOME/CloudServices/reverse_proxy
    configs:
      - source: traefik_config
        target: ~/CloudServices/reverse_proxy
        uid: '103'
        gid: '103'
        mode: 0600
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cloud_cli.entrypoints=https"
        - "traefik.http.routers.cloud_cli.service=cloud_cli"
        - "traefik.http.routers.cloud_cli.rule=Host(`cli.cpanel.csp.cloud.premier-ictc.com`)"
        - "traefik.http.services.cloud_cli.loadbalancer.server.port=22"

  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      LOG_LEVEL: DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_overlay
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ee:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - datastore_portainer:/data
    networks:
      - public_overlay
      - agent_overlay
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.rule=Host(`portainer.cpanel.csp.cloud.premier-ictc.com`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # Edge
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.entrypoints=https"
      - "traefik.http.routers.edge.rule=Host(`edge.cpanel.csp.cloud.premier-ictc.com`)"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"

  # cpanel:
  #   # The official Teleport docker image
  #   image: public.ecr.aws/gravitational/teleport:13
  #   networks:
  #     - "control_overlay"
  #   # ports:
  #   #   - "3080"
  #   volumes:
  #     - ./sso:/etc/teleport
  #     - datastore_teleport:/var/lib/teleport
  #   labels:
  #     - "traefik.enable=true"
  #     # Proxy 
  #     - "traefik.http.routers.cpanel.entrypoints=https"
  #     - "traefik.http.routers.cpanel.service=cpanel"
  #     - "traefik.http.routers.cpanel.rule=Host(`*.cpanel.csp.cloud.premier-ictc.com`)"
  #     # - "traefik.http.routers.cpanel.rule=Host(`cpanel.csp.cloud.premier-ictc.com`)"
  #     - "traefik.http.services.cpanel.loadbalancer.server.port=3080"
  #     # Auth
  #     - "traefik.http.routers.sso.entrypoints=https"
  #     - "traefik.http.routers.sso.service=cpanel"
  #     - "traefik.http.routers.sso.rule=Host(`sso.csp.cloud.premier-ictc.com`)"
  #     - "traefik.http.services.sso.loadbalancer.server.port=3025"

