annotations:
  artifacthub.io/changes: |
    - "[Changed]: Upgrade Argo events controller to v1.7.2-cap-CR-14600"
apiVersion: v2
appVersion: v1.7.2-cap-CR-14600
description: A Helm chart for Argo Events, the event-driven workflow automation framework
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-events/assets/logo.png
keywords:
- argoproj
- argo-events
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-events
sources:
- https://github.com/argoproj/argo-events
version: 2.0.5-1-cf-init
