{{- $internalRouterContext := deepCopy . }}
{{- $_ := set $internalRouterContext "Values" (get .Values "internal-router") }}
{{- $_ := set $internalRouterContext.Values "global" (get .Values "global") }}
{{- include "internal-router.resources.service" $internalRouterContext }}