
{{- define "event-reporters.events-reporter.sa"}}
  {{- if .Values.events.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "event-reporters.events-reporter.serviceAccountName" .}}
  labels:
    {{- include "event-reporters.events-reporter.labels" . | nindent 4 }}
  {{- end }}
{{- end }}