{{- if .Values.global.runtime.gitCredentials.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codefresh-gitops-runtime.runtime-gitcreds.password.default-secret-name" . }}
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.global.runtime.gitCredentials.password.value | b64enc }}
{{- end }}