{{- $appProxyContext := deepCopy . }}
{{- $_ := set $appProxyContext "Values" (get .Values "app-proxy") }}
{{- $_ := set $appProxyContext.Values "global" (get .Values "global") }}
{{- include "cap-app-proxy.resources.service" $appProxyContext }}