{{- define "internal-router.resources.sa" }} 
  {{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "internal-router.serviceAccountName" . }}
  labels:
    {{- include "internal-router.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
